# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

# Creates a pull request from `release/*` branches targeting the repo's default branch.
# Runs on every push to `release/*`.
# Note: you'll need to add a personal access token to your repo, `PERSONAL_ACCESS_TOKEN`.

name: Merge Release Into Main

on:
  push:
    branches:
      - 'release/*'

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: ":robot: _Automated Pull Request_ :robot: <br><br>Merging **${{ github.ref_name }}** into **${{ github.event.repository.default_branch }}**. <br><br> :warning: _If there are conflicts, close this PR, resolve the conflicts manually on an intermediate branch, then open a new PR._"
          pr_reviewer: "jessesquires"
          pr_assignee: "jessesquires"

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: enable automerge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge
